### ISSUE TITLE
What is `times` in the Fibonacci problem?

### ISSUE THREAD

**Issue by mybearworld** [face-hh/subterfuge#1]
I have written a function that gets in the index and returns the nth fibonacci number, but I've not used the `times` parameter, and my code is failing.

What is `times`?

Some sample output:
```js
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13].forEach((index) => {
  console.log(`fibonacci(${index}) => ${fibonacci(index)}`);
});
///
fibonacci(1) => 1
fibonacci(2) => 1
fibonacci(3) => 2
fibonacci(4) => 3
fibonacci(5) => 5
fibonacci(6) => 8
fibonacci(7) => 13
fibonacci(8) => 21
fibonacci(9) => 34
fibonacci(10) => 55
fibonacci(11) => 89
fibonacci(12) => 144
```

**Comment by face-hh** [comment]
Times is the amount of times you have to run the sequence, for example:

times = 10

[1, 1, 2, 3, 5, 8, 13, 21], and so on until the amount of times we've done it reaches 10.

Im definitely going to document this step more once I'll be free, it seems it's too confusing

**Comment by mybearworld** [comment]
Oh, that makes sense, thanks! So is `index` the starting index? Should `fibonacci(3, 2)` be `[2, 3]`?

**Comment by face-hh** [comment]
While checking your function, index is always 2
