### ISSUE TITLE
compactObject function name gets marked as locked feature

### ISSUE THREAD

**Issue by idkhow2type** [face-hh/subterfuge#3]
The regex for matching the `Object` feature is falsely matching the function name `compactObject` in problem 06, making it impossible to pass without unlocking `Object`.

This problem is present with other symbols and when matching comments as well, but those aren't as breaking as this.

**Comment by face-hh** [comment]
Will fix in a few hours

**Comment by mybearworld** [comment]
I ran into the same issue - you can set `global["compactObject"]` as a workaround.

**Comment by mybearworld** [comment]
Same thing applies to <code>findTheD<strong>if</strong>ference</code>

**Comment by face-hh** [comment]
fixed in v1.0.1
