### ISSUE TITLE
The 4th level seems to have been replaced with "some name"

### ISSUE THREAD

**Issue by BlockOG** [face-hh/subterfuge#8]
You probably didn't mean to change it from checking if an object is empty
https://github.com/face-hh/subterfuge/blob/2a8766b8cf04b0a2527188a532f534cb85043533/src/data/savedata.json#L275

**Comment by face-hh** [comment]
Gosh darn I hate the fact that I've stored everything in the same file as the game data...

The old code must be available in a previous commit, if anyone's willing to open a pull request fixing it, I'll merge it.

Otherwise, I'll fix it in about 6 hours
